teamspeak3server:
  image: fgracia/teamspeak3-server:3.8.0
  ports:
   - "9987:9987/udp"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /<local-data-for-database-and-logs>:/data
  restart: always
